a = input('Digite algo: ')
print('O tipo primitivo desse valor é', type(a))
print(f'É númerico?', {a.isnumeric()})
print(f'É alfanúmerico?', {a.isalnum()})
print(f'É alfabético?', {a.isalpha()})
print(f'Esta em maiusculas?', {a.isupper()})
print(f'Esta em minusculas?', {a.islower()})
print(f'Esta Capitalizada?', {a.istitle()})
print(f'Só tem espaço?', {a.isspace()})
