nome = str(input('Digite o seu nome completo: ')).strip()
print('Seu nome em maiúsculas é', nome.upper())
print('Seu nome em minúsculas é', nome.lower())
print(f'Seu nome completo tem {(len(nome) - nome.count(" "))} letras')
sepa_nome = nome.split()
print(f'Primeiro nome é {sepa_nome[0]} e tem {len(sepa_nome[0])} letras.')
