nome = str(input('Digite seu nome completo: ')).strip()
print('Muito prazer em te conhecer!')
fatia = nome.split()
print('Seu primeiro nome é {}'.format(fatia[0]))
print('Seu último nome é {}'.format(fatia[len(fatia)-1]))
